[uwsgi]
chdir = /opt/scripts/ip-lookup
module = app:app
venv = /opt/scripts/ip-lookup/venv

pidfile = /run/ip-lookup/ip-lookup.pid
socket = /run/ip-lookup/ip-lookup.sock

chmod-socket = 660
chown-socket = dev:nginx
vacuum = true

master = true

processes = 4
threads = 2

harakiri = 60
harakiri-verbose = true

post-buffering = 8192
buffer-size = 65535

logto = ./log/uwsgi.log